"""followers

Revision ID: 10eac3e15d39
Revises: 2b518700ee56
Create Date: 2023-02-23 08:55:09.933921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10eac3e15d39'
down_revision = '2b518700ee56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
